rule convert_to_upper_case:
    input:
        "{some_name}.txt"
    output:
        "{some_name}.upper.txt"
    shell:
        """
        tr [a-z] [A-Z] < {input} > {output} 
        """

rule concatenate_a_and_b:
    input:
        "{first}.upper.txt",
        "{second}.upper.txt"
    output:
        "{first}_{second}.txt"

    shell:
        """
        echo 'Concatenating {input}' | cat {input[0]} {input[1]} > {output}  
        """
rule shadow_rules :
    input:
	"input.txt"
